import Sidebar from "./components/sidebar/Sidebar";
import "./globals.css";
import { Montserrat } from "next/font/google";

export const metadata = {
  title: "Next/React Sandbox",
  description: "Generated by create next app",
};

// If loading a variable font, you don't need to specify the font weight
const font = Montserrat({ subsets: ["latin"] });

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={font.className}>
        <div className="flex min-h-screen flex-row">
          <Sidebar>{children}</Sidebar>
        </div>
      </body>
    </html>
  );
}
